wordlists:
  - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  - https://adguardteam.github.io/AdGuardSDNSFilter/Filters/adguard_popup_filter.txt
  - https://adguardteam.github.io/HostlistsRegistry/assets/filter_27.txt
  - https://cdn.jsdelivr.net/gh/badmojr/1Hosts@master/Lite/adblock.txt
  - https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/nsfw.txt
  - https://easylist.to/easylist/easylist.txt
  - https://malware-filter.gitlab.io/malware-filter/phishing-filter-agh.txt
  - https://malware-filter.gitlab.io/malware-filter/urlhaus-filter-agh.txt
  - https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&showintro=1&mimetype=plaintext
  - https://phishing.army/download/phishing_army_blocklist_extended.txt
  - https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianExperimentalList%20alternate%20versions/NordicFiltersAdGuardHome.txt
  - https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Malware
  - https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/AWAvenue-Ads-Rule.txt
  - https://raw.githubusercontent.com/durablenapkin/scamblocklist/master/adguard.txt
  - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/hoster.txt
  - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/native.apple.txt
  - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/native.oppo-realme.txt
  - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/native.samsung.txt
  - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/native.vivo.txt
  - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/native.winoffice.txt
  - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/native.xiaomi.txt
  - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.txt
  - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/tif.txt
  - https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt
  - https://raw.githubusercontent.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites/master/hosts
  - https://someonewhocares.org/hosts/zero/hosts 
